name: test

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  write-file:
    runs-on: ubuntu-latest
    outputs:
      git_sha: ${{ steps.write-file.outputs.GIT_SHA }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{github.run_id}} > foobar.txt
      - run: |
          git add .
          git config --global user.name 'svc-automation'
          git config --global user.email 'svc-automation@heuritech.com'
          git commit -m "test"
          git push
      - run: git rev-parse --short HEAD
      - run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Adding markdown
        run: echo '### plan! ' >> $GITHUB_STEP_SUMMARY

  read-file:
    runs-on: ubuntu-latest
    needs: write-file
    steps:
      - run: echo ${{ needs.write-file.outputs.git_sha }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.write-file.outputs.git_sha }}
      - run: cat foobar.txt
#  terraform-apply:
#    if: |
#      always() &&
#      (contains(needs.*.result, 'skipped') || contains(needs.*.result, 'success'))
#    needs: terraform-plan
#    runs-on: ubuntu-latest
#    environment: euprod
#    steps:
#      - name: Require Manual Approval for Production
#        run: echo "🔒 Waiting for manual approval in GitHub UI."
#      - name: step opt
#        run: echo optional
#        if: github.event_name == 'pull_request'
#      - run: echo apply
#      - name: Adding markdown
#        run: echo '### apply! ' >> $GITHUB_STEP_SUMMARY
#
#  terraform-apply2:
#    needs: terraform-plan
#    runs-on: ubuntu-latest
#    environment: euprod
#    steps:
#      - name: Require Manual Approval for Production
#        run: echo "🔒 Waiting for manual approval in GitHub UI."
#
#      - run: echo apply
#      - name: Adding markdown
#        run: echo '### apply2! ' >> $GITHUB_STEP_SUMMARY
#
#  terraform-apply3:
#    needs: terraform-plan
#    runs-on: ubuntu-latest
#    environment: mt_external
#    steps:
#      - name: Require Manual Approval for Production
#        run: echo "🔒 Waiting for manual approval in GitHub UI."
#
#      - run: echo apply
#      - name: Adding markdown
#        run: echo '### apply3! ' >> $GITHUB_STEP_SUMMARY
