name: Terraform Automation

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ needs.parse-command.outputs.environment }}
    if: github.event_name == 'pull_request'
    steps:
      - run: echo plan
      - name: Adding markdown
        run: echo '### plan! ' >> $GITHUB_STEP_SUMMARY
      
  terraform-apply:
    if: |
      always() && 
      (contains(needs.*.result, 'skipped') || contains(needs.*.result, 'success'))
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: euprod
    steps:
      - name: Require Manual Approval for Production
        run: echo "🔒 Waiting for manual approval in GitHub UI."

      - run: echo apply
      - name: Adding markdown
        run: echo '### apply! ' >> $GITHUB_STEP_SUMMARY

  terraform-apply2:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: euprod
    steps:
      - name: Require Manual Approval for Production
        run: echo "🔒 Waiting for manual approval in GitHub UI."

      - run: echo apply
      - name: Adding markdown
        run: echo '### apply2! ' >> $GITHUB_STEP_SUMMARY

  terraform-apply3:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: mt_external
    steps:
      - name: Require Manual Approval for Production
        run: echo "🔒 Waiting for manual approval in GitHub UI."

      - run: echo apply
      - name: Adding markdown
        run: echo '### apply3! ' >> $GITHUB_STEP_SUMMARY
